### ISSUE TITLE
"Archivierung" der Orders

### ISSUE THREAD

**Issue by Sunflower90** [ca057/kirjanystaevaet#11]
Zu diesem Orderproblem in der Datenbank.

Es soll dem Nutzer ermöglicht werden, seine Bestellungen, die er getätigt hat, einzusehen.
Problem: Ändern sich Daten in Book (Preis!), ändern die sich auch in der Order. Das sollte nicht sein.

Lösungsidee:
Es wird eine weitere Tabelle "Bestellliste" (Namensvorschläge gerne gehört) zwischen Book und Order gelegt. Die enthält als Identifizierer die Ordernumber, außerdem die ISBN (um wieder auf alle Daten von Book zu kommen), dann den Preis (Preis von Book zum Zeitpunkt der Bestellung) und die Anzahl des bestellten Produkts.
Order widerum enthält mehrere Bestelllisten (Name nicht gut gewählt, was haltet ihr von Orderitems?).

Zur Veranschaulichung seht eine Skizze des Schemas im Anhang. 

Die Frage ist: Was außer Preis muss außerdem "archiviert" werden. Meiner Meinung nach nichts. Ändern sich andere Daten (Autor, Titel) dann haben wir auch ein anderes Bookobjekt mit einer anderen ISBN. Und Beschreibung und Bild empfinde ich nicht als wichtig genug zum Archivieren, weshalb da immer auf die Daten des aktuellen Bookobjekts zugeriffen werden sollte.

Ich bitte um ein Feedback, was ihr von diesem Schema haltet.
![img_20160106_112119](https://cloud.githubusercontent.com/assets/12029272/12140544/10cff868-b469-11e5-906f-b7c67f759384.jpg)

**Comment by ca057** [comment]
Eine Bestellung besteht aus einer Menge von Bestelllisten/Orderitems? Klingt doch eigentlich ganz gut.

Beim Bild stimme ich dir zu, wir fragen das sowieso über die ISBN ab (ISBN entspricht Dateinamen). Das heißt, ändert sich Autor... = ändert sich die ISBN = ändert sich die Bild-URL. Ich sehe es wie du, wichtig ist nur der ISBN den Preis zum Bestellzeitpunkt zuzuordnen.

**Comment by HannesT117** [comment]
Wir sollten im Abschlussbericht auf jeden Fall darauf hinweisen, dass es eigentlich auch Hibernate-Möglichkeiten zur Versionsverwaltung gibt, wir das aber zu spät entdeckt haben ...
