### ISSUE TITLE
Welche Felder sind von Open Search betroffen

### ISSUE THREAD

**Issue by Sunflower90** [ca057/kirjanystaevaet#12]
Welche Felder sollten von Open Search betroffen sein? Wirklich alle? 

Ich würde vorschlagen:
Author
Title
Category
ISBN
Description

Ich bitte um eure Meinung!

**Comment by ghost** [comment]
Titel, Autor, ISBN, Publisher :)
Liebe Grüße

**Comment by ca057** [comment]
Meine Prioritäten wären wie folgt:
Titel, Author, Category, ISBN, Year, Description.
