### ISSUE TITLE
Suche umbauen: Autor*in trennen in Vor- und Nachname

### ISSUE THREAD

**Issue by ca057** [ca057/kirjanystaevaet#13]
Bei der Implementierung der getBooksByMetadata-Methode sind einige Fragen für mich offen:
- Der Nutzer gibt in der Suche bei Autor einen Namen ein --> Welches Searchfield muss ich nehmen? Oder ändern wir das Frontend, so dass bei der Suche Vor- und Nachname eingegeben werden muss?
- Das Jahr, welches bei der Suche eingegeben wird entspricht dem pubdate-Key?

**Comment by Sunflower90** [comment]
Ehm, wir sind davon ausgegangen, dass auch in der Eingabe deutlich zwischen Vor- und Nachname unterschieden wird.
Wir können auch mal gemeinsam überlegen, ob und wie man das anders gestalten könnte.

**Comment by Sunflower90** [comment]
Zum Jahr: Gut, dass wir alles immer so gut ausgemacht haben :+1: 
In der Datenbank wird pubdate als z.B. "April 7, 2004" angegeben.
Ich nehme an, in der Suche kann aber nur nach Jahr gesucht werden?

**Comment by ca057** [comment]
Autor getrinnt in Vor- und Nachname, erledigt.
