### ISSUE TITLE
Wie wird Preis bei der Suche angegeben? Werden ALLE Searchfields in der Suche angeboten?

### ISSUE THREAD

**Issue by Sunflower90** [ca057/kirjanystaevaet#14]
Wird bei der Suche Preis berücksichtigt?
Bzw. gleich die allgemeine Frage: Werden bei der Suche ALLE Searchfields zur Verfügung gestellt.

Wie bei Preis? Über einen exakten Wert, oder über einen Range mit Fancy-Schiebereglern?

**Comment by ca057** [comment]
Preis berücksichtigen wir nicht, können wir ja - wenn Zeit ist - am Ende noch einbauen.
