### ISSUE TITLE
NullPointer bei getAllCategories

### ISSUE THREAD

**Issue by Sunflower90** [ca057/kirjanystaevaet#15]
Ich habe festgestellt, dass es zu Fehlern kommt, wenn man z.B. in der View auf Java klickt.

Das lässt sich auf folgendes zurückführen:
Es wird wohl CategoryService.getAllCategories aufgerufen.
Diese Methode ist jedoch nicht implementiert.
Es ist nur eine CategoryService.getAllCategoryNames implementiert, die eben alle CategoryNames liefert (als List<String>)

Die Frage hier: Was braucht ihr an der Stelle? Wenn die Strings, verwendet bitte die entsprechende Methode.
Wofür soll die andere Methode sein? Um die IDs zu bekommen? Oder die Categories als Objekte (List<Category>)? Sagt, was hier sinnvoll wäre (wenn überhaupt) und ich implementiere das!

**Comment by Sunflower90** [comment]
Interessante Anmerkung: Bei PHP funktioniert es, bei Java nicht. Da es die Kategorie Java nicht gibt!
Überprüft bitte trotzdem, welche Methode ihr hier verwendet, und für was die andere benutzt werden könnte.

**Comment by ca057** [comment]
Ja, das ist einfach nur noch nicht richtig implementiert. Ich glaube das kommt aus dem Zwischenstand, als es Views schon geben sollte aber noch nicht alle Methoden. Wird erledigt

**Comment by ca057** [comment]
Und gerade gesehen: Das ist gar keine NullPointerException, sondern eine CategoryNotFoundExcpetion. Das ist eine selbstgebaute Exception, die muss noch gefangen werden. Fehlerbehandlung und Anzeige beim Client ist noch ein Task der erledigt werden muss. Das passiert bei Java, weil es die Kategorie in der Datenbank nicht gibt, ich die anfangs zu Testzwecken aber angelegt habe.

**Comment by ca057** [comment]
Erledigt: Wird eine nicht vorhandene Kategorie angefordert, wird man zu einer Übersicht über alle Kategorien umgeleitet.
