### ISSUE TITLE
Was wird zurück gegeben, wenn es keine Ergebnisse gibt?

### ISSUE THREAD

**Issue by Sunflower90** [ca057/kirjanystaevaet#16]
Leere Liste?

**Comment by ca057** [comment]
Leere Liste. 
Controller stellt die Sucheanfrage und bekommt eine Liste zurück und gibt diese dem View - immer, da abstrakt. Wie der View das anzeigt, ist der jeweiligen Implementierung überlassen.

**Comment by HannesT117** [comment]
Kann man das schließen? Siehe auch Issue 27 und den Hinweis auf Optionals.
