### ISSUE TITLE
Services umstrukturieren

### ISSUE THREAD

**Issue by HannesT117** [ca057/kirjanystaevaet#17]
Es würde sich für die Views anbieten, die Services abzuändern. Vermutlich reicht es, wenn wir mit einem weiterarbeiten und dann z.B. eine Methode getAll(Enum entity) haben. MMn würde sich das auch vom Abstraktionslevel auf dieser Ebene anbieten.

**Comment by Sunflower90** [comment]
Bin ich  mir nicht sicher, ob ich das gut finden soll! Lass uns das bitte erst besprechen, bevor du was änderst!
