### ISSUE TITLE
Registrierung für neue User anbieten

### ISSUE THREAD

**Issue by HannesT117** [ca057/kirjanystaevaet#20]

**Comment by HannesT117** [comment]
Es wäre gut, wenn hier schon auf korrekte E-Mail (@) überprüft wird. Implementieren wir zwar weiter unten auch noch, aber dann kommt es erst gar nicht so weit.

**Comment by ca057** [comment]
Überprüfung erfolgt derzeit client-seitig per regulärem Ausdruck, der hat im Lokalteil der Email alle laut wikipedia erlaubten Sonderzeichen enthalten. Können wir aber auch rausnehmen. Wenn wir den Ausdruck auch serverseitig verwenden, passt die eine auf die andere Überprüfung und es gibt keine bösen Überraschungen.
