### ISSUE TITLE
Bestellung: Abfrage notwendig, ob Lieferadresse vorhanden

### ISSUE THREAD

**Issue by HannesT117** [ca057/kirjanystaevaet#24]
User können auch ohne Adresse existieren, daher muss vor einer Bestellung gecheckt werden, dass eine Adresse existiert.

**Comment by ghost** [comment]
Hab zur Bedingung gemacht, dass Street, StreetNumber und Plz nicht null sind, ok?

**Comment by HannesT117** [comment]
Würde bei Street und StreetNumber noch auf leeren String testen.
