### ISSUE TITLE
Errorcode Enums anstatt von Exceptions

### ISSUE THREAD

**Issue by Sunflower90** [ca057/kirjanystaevaet#27]
Thomas hat vorgeschlagen, anstatt Exceptions zu werfen, wenn möglich Errorcode-Enums zu verwenden.
D.h.: Wenn man etwas löschen will, was nicht vorhanden ist, wird das CategoryError.DoesNotExist Enum zurckgegeben.
Die Rückgabe kann dann eine Ebene drüber geprüft werden und dementsprechend darauf reagiert werden.
Was haltet ihr davon?

**Comment by HannesT117** [comment]
Das hat sich jetzt größtenteils erledigt, oder? Für das potentielle Nicht-Vorhandensein von Objekten würde ich (wie im user auch umgesetzt) Optionals vorschlagen.
